<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Объекты недвижимости"); 
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"real_estate", 
	[
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "3",
		"NEWS_COUNT" => "9",
		"USE_FILTER" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"CHECK_DATES" => "N",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/landing/",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"LIST_PROPERTY_CODE" => [
			0 => "PRICE",
			1 => "CLASS",
			2 => "APARTMENTS_SALE",
			3 => "AREA_1_ROOM_FROM",
			4 => "PRICE_1_ROOM_FROM",
			5 => "AREA_2_ROOM_FROM",
			6 => "PRICE_2_ROOM_FROM",
			7 => "AREA_3_ROOM_FROM",
			8 => "PRICE_3_ROOM_FROM",
			9 => "DELIVERY_DATE",
			10 => "FINISHING",
			11 => "",
		],
		"DETAIL_PROPERTY_CODE" => [
			0 => "PRICE",
			1 => "CLASS",
			2 => "FINISHING",
			3 => "ADDRESS",
			4 => "DELIVERY_DATE_DETAIL",
			5 => "WINDOW_HEIGHT",
			6 => "CEILING_HEIGHT",
			7 => "FEATURES_HERO",
			8 => "MORE_PHOTO",
			9 => "ABOUT_PROJECT_GALLERY",
			10 => "BOOKLET_FILE",
  			11 => "CALCULATOR_LINK",
			12 => "FEATURE_4_TEXT",
			13 => "PANORAMA_EMBED_CODE",
			14 => "MAIN_FEATURES",
			15 => "ARCH_TITLE",
			16 => "ARCH_TEXT",
			17 => "ARCH_IMAGE",
			18 => "LEISURE_TITLE",
			19 => "LEISURE_TEXT",
			20 => "LEISURE_FEATURES",
			21 => "LEISURE_IMAGE",
			22 => "ATMOSPHERE_TITLE",
			23 => "ATMOSPHERE_TEXT",
			24 => "ATMOSPHERE_FEATURES",
			25 => "ATMOSPHERE_GALLERY",
			26 => "LAYOUTS",
			27 => "CONSTRUCTION_PHOTOS",
			28 => "CONSTRUCTION_VIDEOS",
			29 => "HOTSPOT_TEXT",
			30 => "HOTSPOT_ICON",
			31 => "HOTSPOT_TOP",
			32 => "HOTSPOT_LEFT",
		],
		"AJAX_MODE" => "Y",
		"DETAIL_FIELD_CODE" => [
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "",
		],
		"COMPONENT_TEMPLATE" => "real_estate",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => [
			0 => "",
			1 => "",
		],
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"FILE_404" => "",
		"SEF_URL_TEMPLATES" => [
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		]
	],
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>